### PR TITLE
Fix JSON string comparison.

### LINKED ISSUE #474: JSON string comparison seems broken (change in behavior from v0.6.0 and v0.10.0)
In a MySQL server

```
mysql> select json_extract('{"xid":"hello"}', '$.xid') = "hello";
+----------------------------------------------------+
| json_extract('{"xid":"hello"}', '$.xid') = "hello" |
+----------------------------------------------------+
|                                                  1 |
+----------------------------------------------------+
1 row in set (0.00 sec)

mysql> select json_unquote(json_extract('{"xid":"hello"}', '$.xid')) = "hello";
+------------------------------------------------------------------+
| json_unquote(json_extract('{"xid":"hello"}', '$.xid')) = "hello" |
+------------------------------------------------------------------+
|                                                                1 |
+------------------------------------------------------------------+
1 row in set (0.00 sec)
```

With go-mysql-server v0.6.0
```
MySQL [(none)]> select json_extract('{"xid":"hello"}', '$.xid') = "hello";
+--------------------------------------------------------+
| JSON_EXTRACT("{\"xid\":\"hello\"}", "$.xid") = "hello" |
+--------------------------------------------------------+
|                                                      1 |
+--------------------------------------------------------+
1 row in set (0.001 sec)

MySQL [(none)]> select json_unquote(json_extract('{"xid":"hello"}', '$.xid')) = "hello";
+----------------------------------------------------------------------+
| JSON_UNQUOTE(JSON_EXTRACT("{\"xid\":\"hello\"}", "$.xid")) = "hello" |
+----------------------------------------------------------------------+
|                                                                    1 |
+----------------------------------------------------------------------+
1 row in set (0.001 sec)
```

With go-mysql-server v0.10.0
```
MySQL [(none)]> select json_extract('{"xid":"hello"}', '$.xid') = "hello";
+----------------------------------------------------+
| json_extract('{"xid":"hello"}', '$.xid') = "hello" |
+----------------------------------------------------+
|                                                  0 |
+----------------------------------------------------+
1 row in set (0.001 sec)

MySQL [(none)]> select json_unquote(json_extract('{"xid":"hello"}', '$.xid')) = "hello";
ERROR 1105 (HY000): incompatible conversion to SQL type: LONGTEXT
```

The comparison is now false and unquoting fails completely. I believe the root cause is sql.LongText.Convert failing to handle JSONDocument values, so Equals.Compare ends up converting the json value to nil.

### PR DESCRIPTION
**Pull request by ajnavarro**
Fix when a JSON is compared with a string, and apply
unquote as MySQL does.

Fixes #474 

Signed-off-by: Antonio Navarro Perez <antnavper@gmail.com>

### CODE REVIEW

File: sql/stringtype.go [hunk 1]
```diff
@@ -272,7 +273,15 @@ func (t stringType) Convert(v interface{}) (interface{}, error) {
 			return "", nil
 		}
 
-		return s.ToString(nil)
+		str, err := s.ToString(nil)
```
Comment (andremarianiello) [inline sql/stringtype.go:276]: Should this case be handling all JSONValues, not just JSONDocuments?

Comment (ajnavarro) [reply sql/stringtype.go:276]: I just leave as it was, but makes sense. If we use `JSONValue` then we need to remove the following piece of code:
```go
if s.Val == nil {
	return "", nil
}
```
tests still pass without it.

Comment (andremarianiello) [reply sql/stringtype.go:276]: If we don't handle arbitrary JSONValues somehow in this function then JSONValues that aren't JSONDocuments won't be supported, right? Are users supposed to be able to use their own implementations of JSONValue?

Comment (ajnavarro) [reply sql/stringtype.go:272]: Changed! Also, it fixes another bug related to JSON null values. They were translated to "" instead of "null"

**Review by zachmu — APPROVED** [review]
Thanks for the contribution, Antonio!
